# Generated by Django 3.1.4 on 2020-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='weblink',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
