# Generated by Django 3.1.4 on 2020-12-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='channel_name',
            field=models.CharField(default='https://www.youtube.com', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='Youtube Channel', max_length=255),
        ),
    ]
