# Generated by Django 3.1.5 on 2021-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210102_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('nikon', 'Nikon'), ('sony', 'Sony'), ('canan', 'Canan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('coding', 'Coding'), ('gaming', 'Gaming')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'Large'), ('small', 'Small'), ('solo', 'Solo'), ('dute', 'Dute')], max_length=255),
        ),
    ]
