# Generated by Django 3.1.5 on 2021-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_auto_20210114_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'Sony'), ('canan', 'Canan'), ('nikon', 'Nikon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('gaming', 'Gaming'), ('health', 'Health')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('small', 'Small'), ('solo', 'Solo'), ('dute', 'Dute'), ('large', 'Large')], max_length=255),
        ),
    ]
