# Generated by Django 3.1.5 on 2021-01-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_auto_20210115_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canan', 'Canan'), ('sony', 'Sony'), ('nikon', 'Nikon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('coding', 'Coding'), ('health', 'Health')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'Solo'), ('large', 'Large'), ('dute', 'Dute'), ('small', 'Small')], max_length=255),
        ),
    ]
